// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdGg6wZgEh3jtwcH9OyU10av9wY45xJsk',
    appId: '1:373439335357:web:6451cb76c4c81f5820e0d4',
    messagingSenderId: '373439335357',
    projectId: 'zaitecfctnutripro1',
    authDomain: 'zaitecfctnutripro1.firebaseapp.com',
    storageBucket: 'zaitecfctnutripro1.firebasestorage.app',
    measurementId: 'G-PG3711EBG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOE_MRr9zpWIjRivETJ2Wzp443wPF7KSg',
    appId: '1:373439335357:android:f28fd3a1a137c37620e0d4',
    messagingSenderId: '373439335357',
    projectId: 'zaitecfctnutripro1',
    storageBucket: 'zaitecfctnutripro1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdGg6wZgEh3jtwcH9OyU10av9wY45xJsk',
    appId: '1:373439335357:web:d660d4ee2d25643920e0d4',
    messagingSenderId: '373439335357',
    projectId: 'zaitecfctnutripro1',
    authDomain: 'zaitecfctnutripro1.firebaseapp.com',
    storageBucket: 'zaitecfctnutripro1.firebasestorage.app',
    measurementId: 'G-QXHX2D7C6V',
  );
}
